### ISSUE TITLE
tie sleeps closer to the thing to which they belong

### ISSUE THREAD

**Issue by wchristian** [thaena/AldensBot#1]
sleeps are important for your own safety, so you want to avoid forgetting them where they need to be. at the same time a practice of putting sleeps at the end of each tree makes the code harder to reason about

there's two ways to solve this:
1. put the sleeps at the start of a loop always, and only if there's a loop that needs sleeps
2. construct the loop such that it is a function in which an input function is called, and then slept

**Comment by thaena** [comment]
Fixed in 22fab0ad40ed94c921e504a9e026201379c39f23, thank you 🌸
